### PR TITLE
Chain events for oneMKL back end

### LINKED ISSUE #16: possible issue in use of oneAPI DFT
I'm working at Intel using HeFFTe for the distributed 3D-FFT used in GROMACS (see https://gitlab.com/gromacs/gromacs/-/blob/main/src/gromacs/fft/gpu_3dfft_heffte.cpp). HeFFTe's unit tests are failing on PVC platforms, even when using only a single rank and device. The failure mode is not uniformly reproducible, which naturally suggests that the device memory usage is inconsistent with the synchronization.

Since I was interested in single-precision R2C 3D-FFT, I focused on the failures I see in `test_fft3d_r2c`. Sometimes I see a nearly correct result but the first 20 reals in the output buffer are wrong. Since the box is {3,4,5} and 4*5==20, I think there is some wrong indexing going on. If I refactor `heffte::onemkl_executor_r2c::forward()` and `...backward()` so that the `q.wait()` calls move into the for loop over blocks (see https://github.com/icl-utk-edu/heffte/blob/master/include/heffte_backend_oneapi.h#L502), then I observe correct results. The code then looks like
```
    //! \brief Forward transform, single precision.
    void forward(float const indata[], std::complex<float> outdata[], std::complex<float>*) const override{
        if (not init_splan) make_plan(splan);
        for(int i=0; i<blocks; i++)
        {
            oneapi::mkl::dft::compute_forward(splan, const_cast<float*>(indata + i * rblock_stride), reinterpret_cast<float*>(outdata + i * cblock_stride))\
;
            q.wait();
        }
    }
```

If those per-block calls to `compute_forward` etc. have distinct memory footprints then the extra synchronization should not help. So I think the memory footprints for each block do overlap, perhaps for the same reason I see wrong results in the first 20 reals of the output buffer. Perhaps blocks are running concurrently and the previous block is over-running its bounds and affecting the calculation of the current block?

I can't see any obvious indexing errors, but I'm not a DFT expert. Do you see anything in the code that would work better? Is there anything you want me to test for you?

### PR DESCRIPTION
**Pull request by mabraham**
This avoids potential races on the working buffers maintained inside the plan shared over all blocks.

Fixes #16

### CODE REVIEW

**Comment by mabraham** [comment]
Nice CI. Who's providing the runners?

**Comment by mabraham** [comment]
This passes all tests repeatedly, using dpcpp, MKL, and Intel MPI on a node with 4 PVC cards.

**Comment by mkstoyanov** [comment]
This is effectively a duplicate of #17 that I did yesterday. If that's all that's needed, we have the fix in two PRs.

The CI is provided by the University of Tennessee's Innovative Computing Lab(ICL-UTK), since this is an ICL project.

File: include/heffte_backend_oneapi.h [hunk 1]
```diff
@@ -294,6 +294,66 @@ namespace backend{
...
+     */
+    template <typename descriptor_type, typename... data_types>
+    void operator()(onemkl_dft_compute_function_type<descriptor_type, data_types...> function,
+                    descriptor_type& plan,
+                    data_types... data_args)
+    {
+        sycl::event e = function(plan, data_args..., events);
+        // Ensure the vector of events does not reallocate unnecessarily
+        events.resize(1);
+        std::swap(events[0], e);
```
Comment (mkstoyanov) [inline include/heffte_backend_oneapi.h:338]: Here is one difference, you only wait for the last event while I wait for all. I guess this may be better, although I'm not a fan of the variadrics.

**Comment by mkstoyanov** [comment]
I'm still not sure how this fixes the issue when you say that `options.use_reorder = true;` doesn't fix the problem.

I'm working on getting an access to an Intel GPU, once I can do that, I'll get to the bottom of this.

File: include/heffte_backend_oneapi.h (hunk 1 above)
Comment (mabraham) [reply include/heffte_backend_oneapi.h:338]: Yeah that's probably a tiny enhancement. Avoiding the reallocations is much more important for small N.

>  I'm not a fan of the variadrics

Sure, you live here, not me :-) I hate copy-pasted code. We can certainly have specific `onemkl_dft_in_place_compute_function_type` and `onemkl_dft_out_of_place_compute_function_type` if you prefer to avoid the parameter packs.

Comment (mabraham) [reply include/heffte_backend_oneapi.h:338]: In the meantime I made #18. Haven't thought about your further thoughts yet :-)

Comment (mkstoyanov) [reply include/heffte_backend_oneapi.h:338]: Tomorrow I will be driving out of town so I may be less responsive, but I'm back to work on Monday.

**Comment by G-Ragghianti** [comment]
> Nice CI. Who's providing the runners?

The runners are hosted here at ICL (UTK).  We have the ability to run on nvidia, amd, and intel GPUs, but the intel GPU test is currently disabled.  If you have changes that may affect oneapi on gpu, then it would be good to include the cmake-gpu_intel test in the PR (modification of .github/workflows/main.yaml).

File: include/heffte_backend_oneapi.h (hunk 1 above)
Comment (mabraham) [reply include/heffte_backend_oneapi.h]: I've followed your approach for simplifying the approach for keeping the event. I see your point about avoiding resize, but think it is more important to get the first/only work onto the device queue ASAP by ensuring that the vector is empty in that case. That means having an invariant for the class (so private events member), and sometimes changing the size of the vector in a non-allocating way during keep() - which overlaps with the submitted computation.

**Review by mkstoyanov — APPROVED** [review]
This makes sense now! Thanks for contributing.

**Comment by mkstoyanov** [comment]
@G-Ragghianti Thanks for fixing the `gpu_intel` problem!

**Comment by mkstoyanov** [comment]
There is more than one issue here, but at least we fixed one.
